name: animated_native_splash
description: A package which automates the task of creating an animated splash
  screen in a flutter.
version: 1.2.1
homepage: https://github.com/Rexfordasamoah51/flutter_animated_splash_screen
maintainer: Rexford Asamoah

environment:
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  pedantic: ^1.9.2
  xml: ^5.0.2
  yaml: ^3.1.0

dev_dependencies: null
