name: animated_native_splash
description: A package which automates the task of creating an animated splash
  screen in a flutter.
version: 1.2.3
homepage: https://github.com/Rexfordasamoah51/flutter_animated_splash_screen
maintainer: Rexford Asamoah

environment:
  sdk: ">=2.10.4 <3.0.0"

dependencies:
  xml: ^4.5.1
  yaml: ^2.2.1

dev_dependencies: 
  pedantic: ^1.9.2
